version: '2'

services:
  hass:
    container_name: hass
    image: lroguet/rpi-home-assistant:latest
    network_mode: host
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/home-assistant:/config
    environment:
      - PUID
      - PGID

  portainer:
    container_name: portainer
    image: hypriot/rpi-portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID
      - PGID

  sonarr:
    container_name: sonarr
    image: lsioarmhf/sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ${CONF_DIR}/sonarr:/config
      - ${DATA_DIR}/torrents:/downloads
      - ${DATA_DIR}/movies:/movies
    environment:
      - PUID
      - PGID

  radarr:
    container_name: radarr
    image: lsioarmhf/radarr
    restart: unless-stopped
    volumes:
      - ${CONF_DIR}/radarr:/config
      - ${DATA_DIR}/torrents:/downloads
    environment:
      - PUID
      - PGID

  jackett:
    container_name: jackett
    image: lsioarmhf/jackett
    restart: always
    volumes:
      - ${CONF_DIR}/jackett:/config
      - ${DATA_DIR}/torrents:/downloads
    environment:
      - PUID
      - PGID

  transmission:
    container_name: transmission
    build:
      context: ./docker-transmission-openvpn
      dockerfile: Dockerfile.armhf
    image: haugene/rpi-transmission-openvpn
    restart: always
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/transmission:/config
      - ${DATA_DIR}/torrents:/torrents
    environment:
      - LOCAL_NETWORK=192.168.0.0/24
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - OPENVPN_PROVIDER
      - OPENVPN_CONFIG
      - OPENVPN_OPTS=--ping 10 --ping-exit 30
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/torrents
      - TRANSMISSION_INCOMPLETE_DIR=/torrents/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/torrents/watch
      - TRANSMISSION_RPC_HOST_WHITELIST=home-pi.local
      - PUID
      - PGID

  plex:
    container_name: plex
    image: lsioarmhf/plex
    restart: always
    ports:
      - 32400:32400
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/plex:/config
      - ${DATA_DIR}/movies:/data/movies
      - ${DATA_DIR}/series:/data/tvshows
      - ${DATA_DIR}/mediabox:/data/mediabox
    environment:
      - PUID
      - PGID
