version: '3'

services:
  hass:
    container_name: hass
    image: lroguet/rpi-home-assistant:latest
    network_mode: host
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/home-assistant:/config

  portainer:
    container_name: portainer
    image: hypriot/rpi-portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  organizr:
    container_name: organizr
    image: lsioarmhf/organizr
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${CONF_DIR}/organizr:/config
    environment:
      - PUID
      - GUID

  sonarr:
    container_name: sonarr
    image: lsioarmhf/sonarr
    network_mode: host
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ${CONF_DIR}/sonarr:/config
      - ${DATA_DIR}/torrents:/downloads
      - ${DATA_DIR}/movies:/movies
    environment:
      - PUID
      - PGID

  radarr:
    container_name: radarr
    image: lsioarmhf/radarr
    network_mode: host
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ${CONF_DIR}/radarr:/config
      - ${DATA_DIR}/torrents:/downloads
    environment:
      - PUID
      - PGID

  jackett:
    container_name: jackett
    image: lsioarmhf/jackett
    restart: always
    ports:
      - 9117:9117
    volumes:
      - ${CONF_DIR}/jackett:/config
      - ${DATA_DIR}/torrents:/downloads

  transmission:
    container_name: transmission
    build:
      context: ./docker-transmission-openvpn
      dockerfile: Dockerfile.armhf
    image: haugene/rpi-transmission-openvpn
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/transmission:/config
      - ${DATA_DIR}/torrents:/torrents
    cap_add:
    - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 9091:9091
    restart: always
    environment:
      - LOCAL_NETWORK=192.168.0.0/24
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - OPENVPN_PROVIDER
      - OPENVPN_CONFIG
      - OPENVPN_OPTS=--ping 10 --ping-exit 30
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/torrents
      - TRANSMISSION_INCOMPLETE_DIR=/torrents/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/torrents/watch
      - PUID
      - PGID
